/* eslint-disable @next/next/no-html-link-for-pages */
import { ArrowRight, Camera, Check, ShoppingBag } from "lucide-react";
import { chatGPTSignInPath } from "../chatgpt-auth";

export default function Inscription() {
  return <main className="min-h-screen bg-[#0b0b0b] px-5 py-8 text-white lg:px-10">
    <header className="mx-auto flex max-w-6xl items-center justify-between"><a href="/" className="flex items-center gap-3 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#d6ff4b]/60"><Camera size={17}/></span>Objectif</a><a href="/" className="text-sm text-white/50">Retour à l’accueil</a></header>
    <section className="mx-auto flex min-h-[calc(100vh-100px)] max-w-6xl flex-col justify-center py-16"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#d6ff4b]">Créer votre espace</p><h1 className="mt-4 max-w-3xl font-serif text-5xl leading-[.95] tracking-tight md:text-7xl">Comment souhaitez-vous utiliser la plateforme ?</h1>
      <div className="mt-12 grid gap-4 md:grid-cols-2">
        <article className="group rounded-3xl border border-white/12 bg-white/[.04] p-7 transition hover:border-white/30"><span className="grid h-12 w-12 place-items-center rounded-full bg-white/10"><ShoppingBag/></span><h2 className="mt-8 font-serif text-3xl">Acheter des images</h2><p className="mt-3 max-w-md leading-relaxed text-white/50">Enregistrez vos favoris, achetez des licences et retrouvez vos téléchargements au même endroit.</p><ul className="mt-6 space-y-3 text-sm text-white/70">{["Favoris et collections","Historique des achats","Licences et factures"].map(x=><li key={x} className="flex gap-3"><Check size={17} className="text-[#d6ff4b]"/>{x}</li>)}</ul><a target="_top" href={chatGPTSignInPath("/compte")} className="mt-8 flex items-center justify-between rounded-full bg-white px-5 py-3.5 font-semibold text-black">Créer mon compte <ArrowRight size={18}/></a></article>
        <article className="group rounded-3xl border border-[#d6ff4b]/35 bg-[#d6ff4b] p-7 text-black"><span className="grid h-12 w-12 place-items-center rounded-full bg-black/10"><Camera/></span><h2 className="mt-8 font-serif text-3xl">Vendre mes photographies</h2><p className="mt-3 max-w-md leading-relaxed text-black/60">Créez votre vitrine, publiez vos images, choisissez vos licences et suivez vos revenus.</p><ul className="mt-6 space-y-3 text-sm text-black/75">{["Vitrine professionnelle","Licences et prix maîtrisés","Suivi des ventes et revenus"].map(x=><li key={x} className="flex gap-3"><Check size={17}/>{x}</li>)}</ul><a target="_top" href={chatGPTSignInPath("/onboarding/photographe")} className="mt-8 flex items-center justify-between rounded-full bg-black px-5 py-3.5 font-semibold text-white">Ouvrir mon studio <ArrowRight size={18}/></a></article>
      </div><p className="mt-8 text-center text-sm text-white/35">L’authentification sécurisée identifie votre compte. Les informations professionnelles restent séparées de votre profil public.</p>
    </section>
  </main>;
}
