/* eslint-disable @next/next/no-html-link-for-pages */
import { ArrowUpRight, Camera, CircleDollarSign, Eye, Image as ImageIcon, LayoutDashboard, Plus, Settings, ShoppingBag, TrendingUp, Wallet } from "lucide-react";

const stats = [["Revenus nets","2 840 €","+18 %",CircleDollarSign],["Ventes","47","+9",ShoppingBag],["Solde disponible","1 260 €","",Wallet],["Vues","18 420","+24 %",Eye]] as const;
export default function Studio(){return <main className="min-h-screen bg-[#f3f2ed] text-[#161616] lg:grid lg:grid-cols-[250px_1fr]">
  <aside className="hidden min-h-screen flex-col border-r border-black/10 bg-[#111] p-6 text-white lg:flex"><a href="/" className="mb-12 flex items-center gap-3 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#d6ff4b]/60"><Camera size={17}/></span>Objectif</a><p className="mb-3 text-[11px] font-bold uppercase tracking-[.18em] text-white/35">Studio</p><nav className="space-y-1 text-sm">{[[LayoutDashboard,"Vue d’ensemble","/studio"],[ImageIcon,"Mes photos","#"],[ShoppingBag,"Ventes","#"],[TrendingUp,"Statistiques","#"],[Wallet,"Paiements","#"]].map(([Icon,label,href],i)=><a key={label as string} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${i===0?"bg-white/10 text-white":"text-white/55 hover:text-white"}`} href={href as string}><Icon size={18}/>{label as string}</a>)}</nav><div className="mt-auto border-t border-white/10 pt-5"><a className="flex items-center gap-3 px-3 py-3 text-sm text-white/55" href="/studio/profil"><Settings size={18}/>Mon profil public</a></div></aside>
  <section className="p-5 md:p-9 lg:p-12"><header className="mb-12 flex items-center justify-between"><div><p className="text-sm text-black/45">Mercredi 16 septembre</p><h1 className="mt-1 font-serif text-4xl">Bonjour Rimiscky</h1></div><a href="#" className="flex items-center gap-2 rounded-full bg-black px-5 py-3 text-sm font-semibold text-white"><Plus size={17}/> Ajouter des photos</a></header>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label,value,delta,Icon])=><article key={label} className="rounded-2xl border border-black/8 bg-white p-5"><div className="mb-8 flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-full bg-black/[.05]"><Icon size={17}/></span>{delta&&<span className="text-xs font-semibold text-emerald-700">{delta}</span>}</div><p className="text-sm text-black/45">{label}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{value}</p></article>)}</div>
  <div className="mt-4 grid gap-4 xl:grid-cols-[1.6fr_1fr]"><article className="rounded-2xl bg-[#171717] p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-sm text-white/45">Revenus — 30 derniers jours</p><p className="mt-1 text-3xl font-semibold">1 760 €</p></div><span className="rounded-full border border-white/15 px-3 py-1.5 text-xs">30 jours</span></div><div className="mt-12 flex h-44 items-end gap-2">{[35,52,44,74,61,88,68,92,78,100,83,94].map((h,i)=><div key={i} className="flex-1 rounded-t bg-[#d6ff4b] opacity-80" style={{height:`${h}%`}}/>)}</div></article><article className="rounded-2xl bg-[#d6ff4b] p-6"><p className="text-sm font-semibold">Photo la plus vendue</p><div className="mt-5 h-44 overflow-hidden rounded-xl"><img src="https://images.unsplash.com/photo-1744616450607-1bc6cf82b87f?auto=format&fit=crop&w=800&q=85" alt="Rouge manifeste" className="h-full w-full object-cover"/></div><div className="mt-4 flex justify-between"><div><p className="font-serif text-xl">Rouge manifeste</p><p className="text-sm text-black/55">12 ventes · 486 € nets</p></div><ArrowUpRight/></div></article></div>
  <article className="mt-4 overflow-hidden rounded-2xl border border-black/8 bg-white"><div className="flex items-center justify-between border-b border-black/8 p-5"><h2 className="font-serif text-2xl">Ventes récentes</h2><a className="text-sm font-semibold" href="#">Tout afficher</a></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="text-black/40"><tr>{["Photo","Licence","Date","Montant brut","Commission","Net"].map(x=><th key={x} className="px-5 py-4 font-medium">{x}</th>)}</tr></thead><tbody>{[["Rouge manifeste","Commerciale","Aujourd’hui","72 €","10,80 €","61,20 €"],["Lignes silencieuses","Éditoriale","Hier","35 €","5,25 €","29,75 €"],["Le mouvement","Personnelle","14 sept.","19 €","2,85 €","16,15 €"]].map(r=><tr key={r[0]} className="border-t border-black/[.06]">{r.map((c,i)=><td key={c} className={`px-5 py-4 ${i===5?"font-semibold":""}`}>{c}</td>)}</tr>)}</tbody></table></div></article>
  <p className="mt-5 text-xs text-black/40">Données de démonstration — aucun paiement réel n’est connecté à cette version.</p></section>
  </main>}
