import {test,expect} from "@playwright/test";
import {execFileSync} from "node:child_process";
import sharp from "sharp";

test("import, live preview, dirty-form guard, publication and unpublication",async({page,request},info)=>{
  const pageErrors:string[]=[];page.on("pageerror",error=>pageErrors.push(error.message));
  await page.goto("/signin-with-chatgpt?return_to=/studio/photos/nouvelle");
  await expect(page).toHaveURL(/\/studio\/photos\/nouvelle/);
  const profile=await page.request.post("/api/photographer/profile",{data:{displayName:"Photographe E2E",username:"photographe-e2e",bio:"Compte isolé de test"}});
  expect(profile.status()).toBe(200);
  const original=await sharp({create:{width:900,height:700,channels:3,background:"#365e78"}}).webp({lossless:true}).toBuffer();
  await expect(page.locator('input[type="file"]')).toBeEnabled();
  await page.locator('input[type="file"]').setInputFiles({name:"test.webp",mimeType:"image/webp",buffer:original});
  await page.getByRole("textbox",{name:"Titre",exact:true}).fill(`Photo ${info.project.name}`);
  await page.getByRole("checkbox").check();
  const uploadResponse=page.waitForResponse(response=>response.url().endsWith("/api/images/upload")&&response.request().method()==="POST");
  await page.getByRole("button",{name:"Importer l’original"}).click();
  const upload=await uploadResponse;expect(upload.status()).toBe(201);
  const {imageId}=await upload.json() as {imageId:string};
  expect((await request.get(`/api/images/${imageId}`)).status()).toBe(401);
  await page.goto(`/studio/photos/${imageId}`);
  await expect(page.getByTestId("image-status")).toHaveText("PROCESSING");
  await page.getByLabel("Description",{exact:true}).fill("Une photographie synthétique de contrôle.");
  await page.getByLabel("Texte alternatif",{exact:true}).fill("Fond bleu avec signature du photographe");
  await page.getByRole("combobox",{name:"Catégorie",exact:true}).selectOption("Nature");
  await page.getByRole("combobox",{name:"Protection de l’aperçu",exact:true}).selectOption("CUSTOM");
  await page.getByLabel("Texte du filigrane",{exact:true}).fill("Studio E2E");
  await page.getByRole("combobox",{name:"Position",exact:true}).selectOption("REPEATED");
  await page.getByRole("button",{name:"Enregistrer",exact:true}).click();
  await expect(page.getByText("Informations enregistrées. Vos aperçus sont en préparation.",{exact:true})).toBeVisible();
  execFileSync(process.execPath,["--import","tsx","scripts/process-images.ts"],{env:{...process.env,PHOTO_LOCAL_STATE:process.env.PHOTO_E2E_STATE},stdio:"pipe"});
  // No reload: the polling must replace PROCESSING and display the protected image.
  await expect(page.getByTestId("image-status")).toHaveText("READY");
  await expect(page.getByRole("button",{name:"Publier",exact:true})).toBeEnabled();
  expect((await request.get(`/api/images/${imageId}/preview`)).status()).toBe(404);
  await page.getByLabel("Texte du filigrane",{exact:true}).fill("Signature modifiée");
  await expect(page.getByRole("button",{name:"Publier",exact:true})).toBeDisabled();
  await page.getByLabel("Texte du filigrane",{exact:true}).fill("Studio E2E");
  await expect(page.getByRole("button",{name:"Publier",exact:true})).toBeEnabled();
  await page.getByRole("button",{name:"Publier",exact:true}).click();
  await expect(page.getByTestId("image-status")).toHaveText("PUBLISHED");
  expect((await request.get(`/api/images/${imageId}/preview`)).status()).toBe(200);
  await expect(page.getByLabel("Titre",{exact:true})).toBeDisabled();
  await page.getByRole("button",{name:"Dépublier pour modifier"}).click();
  await expect(page.getByTestId("image-status")).toHaveText("UNPUBLISHED");
  expect((await request.get(`/api/images/${imageId}/preview`)).status()).toBe(404);
  await page.getByLabel("Texte du filigrane",{exact:true}).fill("Signature nouvelle");
  await page.getByRole("button",{name:"Enregistrer",exact:true}).click();
  await expect(page.getByTestId("image-status")).toHaveText("PROCESSING");
  expect((await request.get(`/api/images/${imageId}/original`)).status()).toBe(404);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:info.outputPath("editor.png"),fullPage:true});
  await page.getByRole("link",{name:"Mes photographies"}).click();
  await expect(page.getByRole("heading",{name:"Mes photographies"})).toBeVisible();
  execFileSync(process.execPath,["--import","tsx","scripts/process-images.ts"],{env:{...process.env,PHOTO_LOCAL_STATE:process.env.PHOTO_E2E_STATE},stdio:"pipe"});
  const row=page.locator(`a[href="/studio/photos/${imageId}"]`);
  await expect(row).toContainText("Prête");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(pageErrors).toEqual([]);
  await page.screenshot({path:info.outputPath("list.png"),fullPage:true});
});
