/* eslint-disable @next/next/no-html-link-for-pages */
import { ArrowLeft, BadgeCheck, Camera, Globe, MapPin } from "lucide-react";

const portfolio = [
  { title: "Rouge manifeste", src: "https://images.unsplash.com/photo-1744616450607-1bc6cf82b87f?auto=format&fit=crop&w=1200&q=88", size: "md:col-span-2 md:row-span-2" },
  { title: "Lignes silencieuses", src: "https://images.unsplash.com/photo-1666932520939-d0b0e852c3e8?auto=format&fit=crop&w=900&q=88", size: "" },
  { title: "Le mouvement", src: "https://images.unsplash.com/photo-1602212477893-409e6c2d7cad?auto=format&fit=crop&w=900&q=88", size: "" },
];

export default function PhotographerProfile() {
  return <main className="min-h-screen bg-[#f2f0e9] text-[#141414]">
    <header className="flex h-20 items-center justify-between border-b border-black/10 px-5 lg:px-10"><a href="/" className="flex items-center gap-2 text-sm text-black/55"><ArrowLeft size={17}/>Explorer</a><a href="/" className="flex items-center gap-2 font-serif text-xl"><span className="grid h-8 w-8 place-items-center rounded-full border border-black/30"><Camera size={15}/></span>Objectif</a><a href="/inscription" className="rounded-full bg-black px-5 py-2.5 text-sm font-semibold text-white">Vendre mes photos</a></header>
    <section className="relative h-[44vh] min-h-[360px] overflow-hidden bg-[#171717]"><img src={portfolio[0].src} alt="Couverture de Rimiscky Studio" className="h-full w-full object-cover object-[center_35%] opacity-70"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 mx-auto flex max-w-[1450px] items-end gap-5 px-5 pb-8 text-white lg:px-10"><div className="grid h-20 w-20 shrink-0 place-items-center rounded-full border-4 border-white bg-[#d6ff4b] font-serif text-3xl text-black">RS</div><div><div className="flex items-center gap-2"><h1 className="font-serif text-4xl md:text-6xl">Rimiscky Studio</h1><BadgeCheck className="text-[#d6ff4b]"/></div><p className="mt-2 flex items-center gap-2 text-sm text-white/60"><MapPin size={15}/>Paris, France · Mariage, événement, portrait</p></div></div></section>
    <nav className="sticky top-0 z-20 border-b border-black/10 bg-[#f2f0e9]/90 backdrop-blur"><div className="mx-auto flex max-w-[1450px] gap-7 overflow-x-auto px-5 lg:px-10"><a className="border-b-2 border-black py-5 text-sm font-semibold" href="#portfolio">Portfolio</a><a className="py-5 text-sm text-black/45" href="#collections">Collections</a><a className="py-5 text-sm text-black/45" href="#apropos">À propos</a></div></nav>
    <section id="portfolio" className="mx-auto max-w-[1450px] px-5 py-16 lg:px-10"><div className="mb-9 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-black/40">Portfolio sélectionné</p><h2 className="mt-3 font-serif text-5xl">Le regard de Rimiscky</h2></div><p className="max-w-md text-sm leading-relaxed text-black/50">Des images naturelles et cinématiques, pensées pour préserver l’émotion d’un événement et la force d’une présence.</p></div><div className="grid auto-rows-[280px] gap-3 md:grid-cols-3">{portfolio.map((photo)=><a key={photo.title} href="/photo/rouge-manifeste" className={`group relative overflow-hidden bg-black ${photo.size}`}><img src={photo.src} alt={photo.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent opacity-0 transition group-hover:opacity-100"/><p className="absolute bottom-5 left-5 font-serif text-2xl text-white opacity-0 transition group-hover:opacity-100">{photo.title}</p></a>)}</div></section>
    <section id="apropos" className="bg-[#141414] px-5 py-20 text-white lg:px-10"><div className="mx-auto grid max-w-[1450px] gap-12 lg:grid-cols-[1fr_1.4fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d6ff4b]">À propos</p><h2 className="mt-4 font-serif text-5xl">Photographier ce qui mérite de rester.</h2></div><div><p className="max-w-2xl text-lg leading-relaxed text-white/60">Photographe et vidéaste basé à Paris, je réalise des reportages de mariage, d’événement, de portrait et de mode. Mon approche privilégie les gestes vrais, la lumière naturelle et une esthétique élégante.</p><div className="mt-8 flex gap-3"><a href="#" className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-sm"><Globe size={16}/>Site web</a><a href="#" className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2.5 text-sm"><Camera size={16}/>Instagram</a></div></div></div></section>
  </main>;
}
