"use client";
import { ArrowLeft, ArrowRight, Camera, Check, CreditCard, ImagePlus, Store, UserRound } from "lucide-react";
import { useState } from "react";

const steps = [{label:"Compte",icon:UserRound},{label:"Profil",icon:Store},{label:"Professionnel",icon:Camera},{label:"Paiements",icon:CreditCard},{label:"Portfolio",icon:ImagePlus}];

export function PhotographerOnboarding({email,displayName}:{email:string;displayName:string}) {
  const [step,setStep]=useState(0); const [saved,setSaved]=useState(false);
  const next=()=>{setSaved(true); window.setTimeout(()=>{setSaved(false);setStep(s=>Math.min(s+1,4));},350)};
  return <main className="min-h-screen bg-[#f3f2ed] text-[#151515] lg:grid lg:grid-cols-[330px_1fr]">
    <aside className="bg-[#101010] p-7 text-white lg:min-h-screen lg:p-10"><a href="/" className="flex items-center gap-3 font-serif text-xl"><span className="grid h-9 w-9 place-items-center rounded-full border border-[#d6ff4b]/60"><Camera size={17}/></span>Objectif</a><div className="mt-14"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#d6ff4b]">Configuration du studio</p><h1 className="mt-4 font-serif text-4xl leading-tight">Présentez votre travail au monde.</h1><p className="mt-4 text-sm leading-relaxed text-white/45">Vos informations privées, légales et de paiement ne seront jamais affichées sur votre vitrine.</p></div><ol className="mt-12 space-y-2">{steps.map((s,i)=><li key={s.label} className={`flex items-center gap-4 rounded-xl p-3 ${i===step?"bg-white/10":"text-white/40"}`}><span className={`grid h-8 w-8 place-items-center rounded-full border ${i<step?"border-[#d6ff4b] bg-[#d6ff4b] text-black":"border-white/20"}`}>{i<step?<Check size={15}/>:<s.icon size={15}/>}</span><span className="text-sm font-medium">{s.label}</span><span className="ml-auto text-xs">0{i+1}</span></li>)}</ol></aside>
    <section className="flex min-h-screen items-center justify-center p-5 py-12 md:p-12"><div className="w-full max-w-2xl"><div className="mb-9 flex items-center justify-between"><p className="text-sm text-black/45">Étape {step+1} sur 5</p><div className="h-1.5 w-36 overflow-hidden rounded-full bg-black/10"><div className="h-full bg-black transition-all" style={{width:`${(step+1)*20}%`}}/></div></div>{step===0&&<Form title="Vos informations" description="Les informations essentielles pour votre compte." fields={[["Prénom et nom",displayName||"Rimiscky Sambala"],["Adresse e-mail",email],["Pays","France"],["Langue préférée","Français"]]}/>} {step===1&&<Form title="Votre identité de photographe" description="Ces informations composeront votre vitrine publique." fields={[["Nom du photographe ou studio","Rimiscky Studio"],["Nom d’utilisateur","rimiscky"],["Ville","Paris"],["Spécialités","Mariage, événement, portrait"]]}/>} {step===2&&<Form title="Informations professionnelles" description="Facultatif à cette étape. Ces données restent privées." fields={[["Entreprise ou nom commercial",""],["Statut juridique","Micro-entrepreneur"],["Numéro de TVA",""],["Adresse de facturation",""]]}/>} {step===3&&<Panel icon={CreditCard} title="Recevoir vos paiements" text="La connexion à Stripe Connect sera activée dans la phase Paiements. Pour le moment, vous pouvez poursuivre sans saisir de coordonnées bancaires."/>} {step===4&&<Panel icon={ImagePlus} title="Votre première collection" text="Votre studio est prêt. La prochaine phase ajoutera l’import sécurisé, les aperçus protégés et la publication de vos premières images."/>}<div className="mt-10 flex items-center justify-between border-t border-black/10 pt-6"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="flex items-center gap-2 text-sm font-semibold disabled:opacity-25"><ArrowLeft size={17}/> Retour</button>{step<4?<button onClick={next} className="flex items-center gap-3 rounded-full bg-black px-6 py-3.5 font-semibold text-white">{saved?"Enregistré":"Continuer"}{saved?<Check size={18}/>:<ArrowRight size={18}/>}</button>:<a href="/studio" className="flex items-center gap-3 rounded-full bg-[#d6ff4b] px-6 py-3.5 font-semibold">Accéder à mon studio <ArrowRight size={18}/></a>}</div><p className="mt-5 text-xs text-black/40">Démonstration interactive : l’enregistrement serveur sera activé avec la persistance des profils.</p></div></section>
  </main>;
}

function Form({title,description,fields}:{title:string;description:string;fields:string[][]}){return <div><p className="text-xs font-bold uppercase tracking-[.18em] text-black/40">Profil photographe</p><h2 className="mt-3 font-serif text-5xl tracking-tight">{title}</h2><p className="mt-3 text-black/50">{description}</p><div className="mt-9 grid gap-5 sm:grid-cols-2">{fields.map(([label,value])=><label key={label} className="text-sm font-semibold">{label}<input defaultValue={value} className="mt-2 h-12 w-full rounded-xl border border-black/12 bg-white px-4 font-normal outline-none transition focus:border-black"/></label>)}</div></div>}
function Panel({icon:Icon,title,text}:{icon:typeof CreditCard;title:string;text:string}){return <div className="rounded-3xl border border-black/10 bg-white p-8"><span className="grid h-14 w-14 place-items-center rounded-full bg-[#d6ff4b]"><Icon/></span><h2 className="mt-8 font-serif text-5xl tracking-tight">{title}</h2><p className="mt-4 max-w-xl leading-relaxed text-black/50">{text}</p></div>}
