/* eslint-disable @next/next/no-html-link-for-pages */
"use client";
import { ArrowLeft, Camera, Check, Eye, LoaderCircle } from "lucide-react";
import { FormEvent, useState } from "react";

export function ProfileEditor({ email, initialName }: { email: string; initialName: string }) {
  const [status,setStatus]=useState<"idle"|"saving"|"saved"|"error">("idle"); const [message,setMessage]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("saving");setMessage("");const data=Object.fromEntries(new FormData(event.currentTarget));const response=await fetch("/api/photographer/profile",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const result=await response.json() as {error?:string};if(!response.ok){setStatus("error");setMessage(result.error??"Une erreur est survenue.");return}setStatus("saved");setMessage("Profil enregistré.");}
  return <main className="min-h-screen bg-[#f3f2ed] text-[#161616]"><header className="flex h-20 items-center justify-between border-b border-black/10 bg-white px-5 lg:px-10"><a href="/studio" className="flex items-center gap-2 text-sm text-black/55"><ArrowLeft size={17}/>Retour au studio</a><a href="/" className="flex items-center gap-2 font-serif text-xl"><Camera size={19}/>Objectif</a><a href="/photographes/rimiscky" className="flex items-center gap-2 rounded-full border border-black/15 px-4 py-2 text-sm font-semibold"><Eye size={16}/>Voir ma vitrine</a></header>
    <form onSubmit={submit} className="mx-auto max-w-5xl px-5 py-12 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-black/40">Profil public</p><h1 className="mt-3 font-serif text-5xl leading-none">Votre identité visuelle commence ici.</h1><p className="mt-5 leading-relaxed text-black/50">Ces informations apparaîtront sur votre vitrine. Votre e-mail, vos informations légales et vos données de paiement restent privés.</p><div className="mt-8 rounded-2xl bg-[#d6ff4b] p-5"><p className="text-sm font-semibold">Compte connecté</p><p className="mt-1 text-sm text-black/55">{email}</p></div></div>
      <div className="rounded-3xl border border-black/8 bg-white p-6 md:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field name="displayName" label="Nom du photographe ou studio" defaultValue={initialName||"Rimiscky Studio"}/><Field name="username" label="Nom d’utilisateur" defaultValue="rimiscky" prefix="objectif.fr/photographes/"/><Field name="city" label="Ville" defaultValue="Paris"/><Field name="country" label="Pays" defaultValue="France"/><Field name="websiteUrl" label="Site web" defaultValue="https://rimiscky-portfolio.vercel.app/" wide/><label className="text-sm font-semibold sm:col-span-2">Biographie<textarea name="bio" rows={6} defaultValue="Photographe et vidéaste spécialisé dans le mariage, l’événement, le portrait et la mode. Une approche naturelle, cinématique et attentive aux émotions." className="mt-2 w-full resize-none rounded-xl border border-black/12 bg-[#fafafa] p-4 font-normal leading-relaxed outline-none focus:border-black" maxLength={600}/><span className="mt-1 block text-right text-xs font-normal text-black/35">600 caractères maximum</span></label></div>
        {message&&<p role="status" className={`mt-5 rounded-xl px-4 py-3 text-sm ${status==="error"?"bg-red-50 text-red-700":"bg-emerald-50 text-emerald-700"}`}>{message}</p>}
        <div className="mt-7 flex justify-end"><button disabled={status==="saving"} className="flex items-center gap-3 rounded-full bg-black px-6 py-3.5 font-semibold text-white disabled:opacity-60">{status==="saving"?<LoaderCircle className="animate-spin" size={18}/>:status==="saved"?<Check size={18}/>:null}{status==="saving"?"Enregistrement…":"Enregistrer le profil"}</button></div></div></div></form></main>;
}

function Field({name,label,defaultValue,prefix,wide=false}:{name:string;label:string;defaultValue:string;prefix?:string;wide?:boolean}){return <label className={`text-sm font-semibold ${wide?"sm:col-span-2":""}`}>{label}{prefix&&<span className="ml-2 text-xs font-normal text-black/35">{prefix}</span>}<input name={name} defaultValue={defaultValue} className="mt-2 h-12 w-full rounded-xl border border-black/12 bg-[#fafafa] px-4 font-normal outline-none focus:border-black" required={name==="displayName"||name==="username"}/></label>}
